name: Bats Test

on:
  pull_request:
  workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-24.04
    
        steps:
        - uses: actions/checkout@v2

        - name: Set up Bats and Bats-support
          run: |
            sudo apt-get update
            sudo apt-get install -y bats bats-support bats-assert

        - name: Run Bats tests
          run: |
            bats test/